# 服务端口号
server:
  port: 8001

spring:
  application:
    name: microservicecloud-provider   # 对外暴露的服务名称
  ## 数据源配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/microservicecloud?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize : 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, logback
    connectionProperties : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  ## json时间格式设置
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    lease-renewal-interval-in-seconds: 10


mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  type-aliases-package: com.hungkuei.model
  mapper-locations: classpath:mybatis/mapper/**/*.xml

##日志配置
logging:
  level:
    com.hungkuei: DEBUG


info:
  app.name: microservicecloud
  author: hungkuei
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  date: 2019-08-18 15:22:00


